### ISSUE TITLE
Traverse folders in Import Directory

### ISSUE THREAD

**Issue by bullmoose20** [gaseous-project/gaseous-server#141]
**I have an already semi organized roms directory that has subdirectories per platform. As gaseous does not support dropping folders into the import directory, I need to copy and paste them. The issue is that this then creates a duplicate when the same rom name exists in two different platforms. 

**Describe the solution you'd like**
Support the ability to drop files and folders into the import directory

**Describe alternatives you've considered**
I don't really have a clean solution at this point other than mass renaming files in the roms platform sub folders.

**Comment by michael-j-green** [comment]
The core problem you describe here is largely taken care of by the libraries feature which will be available in https://github.com/gaseous-project/gaseous-server/milestone/3 (see PR: https://github.com/gaseous-project/gaseous-server/pull/147).

But I'll complete directory traversing in the import folder anyway since it's a useful feature to have.
