### ISSUE TITLE
On the settings page and library page show total number of roms per platform

### ISSUE THREAD

**Issue by bullmoose20** [gaseous-project/gaseous-server#143]
**Is your feature request related to a problem? I need to know the total number per platform to understand if the roms got added properly 

**Describe the solution you'd like**
On library page, you have a filter by platform. Add the count of roms per platform there. Secondly, on settings page, space is broken down by platform so add count per platform there.

**Describe alternatives you've considered**
Currently I would need to go into the imported directory per platform and get directory file counts. This is not really feasible.

**Comment by michael-j-green** [comment]
For the filter page, rather than the number of Roms on the platform, I've gone with the number of games available for that platform. I feel like that's more in keeping with the spirit of the page:
<img width="210" alt="Screenshot 2023-10-16 at 4 43 54 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/111ffcc8-b392-43e2-aa74-d0c528baebdd">

On the status page, I now display the number of actual rom images available per platform:
<img width="976" alt="Screenshot 2023-10-16 at 4 49 21 pm" src="https://github.com/gaseous-project/gaseous-server/assets/84688932/8a12e133-5db9-43b4-b374-61b65814b781">

What do you think?

**Comment by MartynKeigher** [comment]
Loving this addition!! Excellent work! 💯
