### ISSUE TITLE
Unknown Default Login Credentials

### ISSUE THREAD

**Issue by MichelfrancisBustillos** [gaseous-project/gaseous-server#362]
**Describe the bug**
When starting Gaseous for the first time, the webUI prompts for a username and password. I have tried most of the 'common' options as well as the DB user/pass from the docker-compose file, however, none have worked so far. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04 virtualized
 - Browser Chrome
 - Version 1.7.3

**Comment by michael-j-green** [comment]
Hi @MichelfrancisBustillos; this has come up a few times lately, and I'm not sure what's causing it. I'll be examining it as part of the 1.8 version I'm working on now.

What's supposed to happen is that when you start Gaseous for the first time, it's supposed to take you through the process of creating an admin account. As you've found out, sometimes it's not redirecting.

You should be able to manually navigate to ``/first.html``, which should force Gaseous to present the new admin user creation screen.

**Comment by MichelfrancisBustillos** [comment]
That worked. Another question (likely due to my lack of familiarity with Docker). How would you point Gaseous at a folder on your filesystem that contains your ROMS?

**Comment by michael-j-green** [comment]
Great to hear! I'm going to keep this issue open to remind me to fix it for the next version :D 

As for adding extra local directories, you would do that in the docker-compose.yml file.

Under volumes for the gaseous-server container, add a line like the following (remember to add white space to line it up with the existing volume entries): ``- <local host directory>:<container mount directory>:ro``

For example, if the path on your host is ``/mnt/tank/games/roms``, and you want to make it available inside the container as ``/roms``, the volume mount entry would be ``- /mnt/tank/games/roms:/roms:ro`` (the ``:ro`` means that the directory will be mounted read-only - I recommend this since Gaseous has no reason to modify this directory, and it's good security practice).

Then follow the instructions at https://github.com/gaseous-project/gaseous-server/wiki/Adding-ROMs#custom-library to create a custom library.

Using the above example, you would use ``/roms`` as the directory for the custom library.

Hope this helps!

**Comment by wwwescape** [comment]
I am having the same issue. However, the workaround suggested only worked the first time.

I had to redo my entire Docker setup again but now whenever I navigate to `http://localhost:5198/pages/first.html`, it automatically redirects to `http://localhost:5198/pages/login.html` again. Now I am unable to do anything.

Any ideas?

**Comment by devanteweary** [comment]
> I am having the same issue. However, the workaround suggested only worked the first time.
> 
> I had to redo my entire Docker setup again but now whenever I navigate to `http://localhost:5198/pages/first.html`, it automatically redirects to `http://localhost:5198/pages/login.html` again. Now I am unable to do anything.
> 
> Any ideas?

Getting the exact same issue, except going to first.html just redirects to login.html.  
I can't get in. I'm going to have to uninstall and reinstall.
