### ISSUE TITLE
Ability to go back in a filtered list

### ISSUE THREAD

**Issue by Flyingfufu** [gaseous-project/gaseous-server#59]
If I filter a list of game and enter in one of them to see the details, there is no way to come back directly to the filtered list.

Would be nice to have a button (ie in the top left corner) to be able to go back on the previous (filtered) page.

**Comment by michael-j-green** [comment]
Question for you... the back button, do you think it will be better as:
* A browser back button where it simply executes a back - similar to pressing the back button on the browser. I've noticed this does not always load the filtered list. Or;
* A link that goes back to the library - but this time the filter settings are stored in a cookie. This means that if the page is refreshed, the same filter settings will be loaded.

**Comment by Flyingfufu** [comment]
Either or, but I think the second option is most probably the best.

**Comment by michael-j-green** [comment]
@Flyingfufu; this has been completed (without an actual back button). The browser back button has become more reliable now that the filter settings are stored in a cookie.

Let me know how you go once you get v1.5.0, and if we need to revisit a separate back button, we'll do it. I just couldn't think of a nice way to integrate it into the UI so that it looked the part :)
